export const TRADE_CHANNEL = '📥trades'
export const STATS_CHANNEL = '🤖vaults'
export const TOKEN_CHANNEL = '🟢token'
export const DEPOSITS_CHANNEL = '🏦deposits'
export const TRADER_CHANNEL = '👔traders'
export const ARBS_CHANNEL = '💰arbs'
export const EXPIRY_CHANNEL = '🎯strikes'
