export const degenMessage = [
  "YOLO'd",
  'Feeling Bullish',
  'gm! 🚀',
  'Gud trade',
  'No game, no life',
  'Action bet!!',
  'Fight Beras',
  'Glad, I bought some puts',
  'Green Candles Only, no stop loss',
  '🐵 Apes Strong',
  'been sober for 3 days now. feeling great',
  '🐵 Ape Strategy',
  'reverse iron albatross spread?',
  '🐵 🤝 🐵',
  'Leverage, LFG!!',
  'pamp Fudzy',
  'Apes think alike',
  'Why do we always buy the top?',
  '🦧 ALWAYS WIN',
  'Apes must learn',
  "Wait, so what's my portfolio worth rn?",
  'did we really convert 10k into 700$?',
  'Irresponsibly long',
  'swift recovery of funds inbound',
  'I think this is how the fed works.',
  'Getting rekt fast 101.',
  'Make it all back with 1 trade',
  'Down bad?',
  "I'm so proud of every last one of you guys.",
  'Up only!',
  'Just setting up a comeback story is all.',
  'Completely unpredictable',
  "as long as it's green its a huge improvement over last time",
  "triple the portfolio value now and we'll be close to breakeven",
  'oooo boy, we gmi',
  'literally left it to randomness?',
  'whatever we do the market does the opposite',
  "Can't go wrong more than once",
  'Till expiry or bust',
  'the market exists purely to mock the apes',
]

export function RandomDegen(): string {
  const random = Math.floor(Math.random() * degenMessage.length)
  return degenMessage[random]
}
